namespace ImmichReverseGeo.WorkerProcessFixture;

internal enum ProcessMatrixFault
{
    DomainFailure,
    PreReadyCrash,
    PostReadyCrash,
    MissingTerminal,
    OutputExit,
    InfrastructureExit,
    InvalidInputExit,
    BusyExit,
    CancelledExit,
    TerminalMismatch,
    CompletedLateProtocol,
    CompletedContradictoryExit,
    NeverReady,
    CooperativeCancel,
    Unresponsive,
    UnresponsiveQuiet,
    UnresponsiveTree,
    InvalidUtf8,
    MalformedJson,
    TruncatedJson,
    BlankFrame,
    BomFrame,
    OversizedFrame,
    NonProtocolText,
    UnknownProtocol,
    UnknownVersion,
    UnknownDirection,
    UnknownCategory,
    UnknownType,
    UnknownJobKind,
    CategoryTypeMismatch,
    DuplicateProperty,
    InvalidPayload,
    WrongCorrelation,
    SequenceGap,
    ProtocolBeforeStop,
    SequenceReplay,
    DuplicateReady,
    MissingReady,
    PostTerminal,
    AdditiveProperties,
    AdditiveEnvelope,
    AdditivePayload,
    LosslessPipeBurst,
    LosslessPipeCorruption
}

internal static class ProcessMatrixFaults
{
    private static readonly IReadOnlyDictionary<string, ProcessMatrixFault> Tokens =
        new Dictionary<string, ProcessMatrixFault>(StringComparer.Ordinal)
        {
            ["domain-failure"] = ProcessMatrixFault.DomainFailure,
            ["pre-ready-crash"] = ProcessMatrixFault.PreReadyCrash,
            ["post-ready-crash"] = ProcessMatrixFault.PostReadyCrash,
            ["missing-terminal"] = ProcessMatrixFault.MissingTerminal,
            ["output-exit"] = ProcessMatrixFault.OutputExit,
            ["infrastructure-exit"] = ProcessMatrixFault.InfrastructureExit,
            ["invalid-input-exit"] = ProcessMatrixFault.InvalidInputExit,
            ["busy-exit"] = ProcessMatrixFault.BusyExit,
            ["cancelled-exit"] = ProcessMatrixFault.CancelledExit,
            ["terminal-mismatch"] = ProcessMatrixFault.TerminalMismatch,
            ["completed-late-protocol"] = ProcessMatrixFault.CompletedLateProtocol,
            ["completed-contradictory-exit"] = ProcessMatrixFault.CompletedContradictoryExit,
            ["never-ready"] = ProcessMatrixFault.NeverReady,
            ["cooperative-cancel"] = ProcessMatrixFault.CooperativeCancel,
            ["unresponsive"] = ProcessMatrixFault.Unresponsive,
            ["unresponsive-quiet"] = ProcessMatrixFault.UnresponsiveQuiet,
            ["unresponsive-tree"] = ProcessMatrixFault.UnresponsiveTree,
            ["invalid-utf8"] = ProcessMatrixFault.InvalidUtf8,
            ["malformed-json"] = ProcessMatrixFault.MalformedJson,
            ["truncated-json"] = ProcessMatrixFault.TruncatedJson,
            ["blank-frame"] = ProcessMatrixFault.BlankFrame,
            ["bom-frame"] = ProcessMatrixFault.BomFrame,
            ["oversized-frame"] = ProcessMatrixFault.OversizedFrame,
            ["non-protocol-text"] = ProcessMatrixFault.NonProtocolText,
            ["unknown-protocol"] = ProcessMatrixFault.UnknownProtocol,
            ["unknown-version"] = ProcessMatrixFault.UnknownVersion,
            ["unknown-direction"] = ProcessMatrixFault.UnknownDirection,
            ["unknown-category"] = ProcessMatrixFault.UnknownCategory,
            ["unknown-type"] = ProcessMatrixFault.UnknownType,
            ["unknown-job-kind"] = ProcessMatrixFault.UnknownJobKind,
            ["category-type-mismatch"] = ProcessMatrixFault.CategoryTypeMismatch,
            ["duplicate-property"] = ProcessMatrixFault.DuplicateProperty,
            ["invalid-payload"] = ProcessMatrixFault.InvalidPayload,
            ["wrong-correlation"] = ProcessMatrixFault.WrongCorrelation,
            ["sequence-gap"] = ProcessMatrixFault.SequenceGap,
            ["protocol-before-stop"] = ProcessMatrixFault.ProtocolBeforeStop,
            ["sequence-replay"] = ProcessMatrixFault.SequenceReplay,
            ["duplicate-ready"] = ProcessMatrixFault.DuplicateReady,
            ["missing-ready"] = ProcessMatrixFault.MissingReady,
            ["post-terminal"] = ProcessMatrixFault.PostTerminal,
            ["additive-properties"] = ProcessMatrixFault.AdditiveProperties,
            ["additive-envelope"] = ProcessMatrixFault.AdditiveEnvelope,
            ["additive-payload"] = ProcessMatrixFault.AdditivePayload,
            ["lossless-pipe-burst"] = ProcessMatrixFault.LosslessPipeBurst,
            ["lossless-pipe-corruption"] = ProcessMatrixFault.LosslessPipeCorruption
        };

    internal static bool TryParse(string value, out ProcessMatrixFault fault) =>
        Tokens.TryGetValue(value, out fault);
}
